<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "widget_view"
 *
 * Auto generated by Extension Builder 2015-03-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Backend Widget View',
	'description' => 'Adds a widget view in the backend that enhances the old List view',
	'category' => 'module',
	'author' => 'Radu Mogos',
	'author_email' => 'radu.mogos@pixelplant.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);